### ISSUE TITLE
Fix destructor of `Topology` class

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/ODC#43]
Currently `SubscribeToTaskDoneEvents` is commented in the`Topology` class [here](https://github.com/FairRootGroup/ODC/blob/c834aa25bfc64ca2dc93a0d6a9e03ddb781bc278/fairmq/fairmq/src/Topology.h#L365). The reason is that subscription to events from DDS leads to a crash in the destructor in some cases. The lifetime of the DDS session object is larger than the lifetime of the `Topology` itself. `SubscribeToTaskDoneEvents` uses `this`. An event arriving from DDS after the `Topology` object is already destructed will lead to a crash.

Possible solutions:
* use `std::enable_shared_from_this`,
* unsubscribe from DDS event in the destructor (needs to be supported by DDS)

**Comment by rbx** [comment]
>     * unsubscribe from DDS event in the destructor (needs to be supported by DDS)

+1
