### ISSUE TITLE
Optimization of state changes

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/ODC#5]
@dennisklein @rbx @AnarManafov 
I've created an issue to exchange the information for the optimization strategies.

The fresh logs of DDS-control run you can find here: `/lustre/rz/andrey/.DDS/sessions/a01f4610-137e-4f75-b888-db5b62396b79/2019-09-16-12-31-49`

**Comment by rbx** [comment]
We merged an optimization in the dev branch of FairMQ that could accelerate the accumulation of the state change responses. Please try to run with the latest dev.

**Comment by AndreyLebedev** [comment]
In DDS we use /tmp as sandbox directory for DDS agents in the test now.

Some comparison results:

| Request  | Original |  + /tmp sandbox | + FairMQ optimization |
| ------------- | ------------- | ------------- | ------------- |
| ConfigureRun | 54  | 47 | 42 |
| Start | 8.4  | 6.7 | 6.5 |
| Stop | 7.6  | 6.3 | 6.0 |
| Terminate | 37  | 28 | 26 |

The second column includes time for "/tmp sandbox" optimization. The last column includes both "/tmp sandbox" and " FairMQ optimization".

**Comment by dennisklein** [comment]
Can you rerun with `--verbosity veryhigh --severity debug` passed to the FairMQ devices in the topology and provide the logs (would just need the session log and the agent/device logs, not all the MB-sized files DDS copies around)? Then I will create some plots from it. The numbers still seem very broken.

**Comment by AndreyLebedev** [comment]
@dennisklein I ran the test as you requested. I copied logs to `/lustre/rz/andrey/tmp/dds_logs/log`.

**Comment by rbx** [comment]
@AnarManafov @AndreyLebedev
Can you post the numbers you mentioned today here (and how to reproduce them)?
I am benchmarking our callback (the one for CCustomCmd.subscribe()) with equivalent of 100k devices, and in majority of cases the runtime is well below 0.1 milliseconds. The only time when it reaches above 1ms is when accumulated transition was successful - this happens once in <num_devices> cases (so in your case once in 3600 callbacks). Then the runtime reaches 20-30ms (for 100k entries) because we need to construct a new container to return to the user.

**Comment by dennisklein** [comment]
This plot shows incoming(red) and outgoing(blue) custom commands as logged in the dds agent logs by the `fairmq-*` processes (binned into 1s intervals). For some reason the **combined** outgoing custom command rate seems to be limited:

![agent_cc_time_distribution](https://user-images.githubusercontent.com/297548/65075777-d77b9380-d997-11e9-9c19-96aa332fa3fa.png)

**Comment by AndreyLebedev** [comment]
@rbx @dennisklein Thanks for your investigations. We are implementing more timestamps in the DDS now in order to precisely identify the bottlenecks on our side. We let you know as soon as we have results.

**Comment by dennisklein** [comment]
> We are implementing more timestamps in the DDS now in order to precisely identify the bottlenecks on our side.

You might also be interested in the [CPU Flame Graphs](http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html) and [Off-CPU Flame Graphs](http://www.brendangregg.com/FlameGraphs/offcpuflamegraphs.html) methods to find certain hotspots in the code (eBPF/BCC need a fairly recent Linux kernel 4.7+ or so, but there is also DTrace on macOS I believe which can provide the stacktrace samples).

**Comment by rbx** [comment]
Just a minor thing with the log files ddslogs.tar.gz - it seems that most lines are duplicated, probably not any major issue, but could be some wasted work by whoever prints these lines.
e.g.:
```
2019-09-17 09:59:55.907808   inf    dds-control-server   <0x0001d733:0x00007f6d11f03700>    Received custom command: senderId:18188924030445220538 cmd: main/ProcessorGroup/ExCol_259/Processor_9: queued, CONNECT condition: 3155162245672687454
2019-09-17 09:59:55.907808   inf    dds-control-server   <0x0001d733:0x00007f6d11f03700>    Received custom command: senderId:18188924030445220538 cmd: main/ProcessorGroup/ExCol_259/Processor_9: queued, CONNECT condition: 3155162245672687454
2019-09-17 09:59:55.907854   inf    dds-control-server   <0x0001d733:0x00007f6d11f03700>    Received custom command: senderId:5146070000933838992 cmd: main/ProcessorGroup/ExCol_60/Sampler_0: queued, CONNECT condition: 3155162245672687454
2019-09-17 09:59:55.907854   inf    dds-control-server   <0x0001d733:0x00007f6d11f03700>    Received custom command: senderId:5146070000933838992 cmd: main/ProcessorGroup/ExCol_60/Sampler_0: queued, CONNECT condition: 3155162245672687454
```

**Comment by dennisklein** [comment]
Find my latest measurements here: https://docs.google.com/spreadsheets/d/1pbaGtyQGhMtfHN_JjDkABpbwSMFYIXlvujzEQnqTmVI/edit?usp=sharing

![Timings of EPN demo controller on GSI virgo cluster - 30 09 2019](https://user-images.githubusercontent.com/297548/65910997-22e86580-e3cc-11e9-8b40-4f73b2c6506f.png)

Those include the latest optimization by Alexey in FairMQ, we are now sending proper space-efficient binary protocol message via custom commands (flatbuffers serialization). Also, there was one instance, where we would send two custom command replies at the same time which we consolidated into a single custom command.

**Comment by AndreyLebedev** [comment]
The issue is resolved in the latest releases of ODC, DDS and FairMQ.
